Ridho/APIToken
binary-com/binary-static-ci pull request #3
Opened 2017-04-10 02:47 UTC by ridhomard

Test cases for :

- API Token Form Validation 
- Add New Token 
- Delete Token

2017-04-10 03:28 UTC, negarn commented
failing test?

2017-04-10 03:56 UTC, bijan2007 requested changes
Incorrect method name - NavigateToLoginHistoryPage()

2017-04-10 05:49 UTC, ridhomard commented
@negarn yes its expeceted , since there is a bug in FE. 
@bijan2007 ,, MyBad,, fixed it thanks!

2017-04-11 15:08 UTC, bijan2007 approved these changes

2017-04-11 15:10 UTC, merged