Tested for lost password
binary-com/binary-static-ci pull request #7
Opened 2017-04-13 02:14 UTC by tazeek

Test case should cover:

- Navigating to 'Lost Password' page
- Receiving email along with token
- Validating the new password
- Passwords must contain lowercase, uppercase and number(s)
- Passwords must match
- If user has a real money account, get date of birth
- Going back to 'send token' page, assuming the original token has expired or is invalid

2017-04-13 03:30 UTC, bijan2007 requested changes
Please commit only the files related to your changes

2017-04-13 03:44 UTC, ridhomard requested changes
Need to add test cases .xml

2017-04-13 05:06 UTC, tazeek commented
Performing changes and adding test cases now

2017-04-13 08:44 UTC, ridhomard requested changes
1. Should give more form validation 
2. Should minimise use of manual input (should use constant)
3. Retry link need more validation 
4. User assert.

2017-04-13 18:10 UTC, bijan2007 requested changes
Please resolve the conflicts and travis test should be passing

2017-04-17 15:04 UTC, bijan2007 approved these changes

2017-04-17 15:10 UTC, bijan2007 commented on src/test/java/testCases/Validate_LostPassword.java
> +	public void navigateToLostPasswordPage() {
Please use navigation methods

2017-04-21 02:44 UTC, bijan2007 commented on src/test/java/utility/Constant.java
> +	public static final String URL_Binary = "https://binary.com";
We should check against staging and not production

2017-04-21 02:45 UTC, bijan2007 requested changes
Please look at the comment to test against staging

2017-04-21 02:51 UTC, tazeek commented
Changed url to staging instead of production

2017-04-28 04:10 UTC, bijan2007 approved these changes

2017-07-04 01:36 UTC, bijan2007 commented
Closing this PR as it is outdated

2017-07-04 01:36 UTC, closed without merging