Test case for selfexclusion-limits check
binary-com/binary-static-ci pull request #8
Opened 2017-04-13 02:25 UTC by fanxuricky

2017-04-13 03:27 UTC, bijan2007 commented
Please resolve the conflicts and also remove the output files from the commit

2017-04-13 05:06 UTC, ridhomard reviewed
Please check indentation

2017-04-13 07:55 UTC, ridhomard commented on src/test/java/testCases/Validate_SelfExlcusion_Limits.java
> +				System.out.println("[P]New amount are not allowed to exceed current amount.");;
Can we put assertEqual() here ? and just getText() for the error message - we can validate the correct error message

2017-04-13 07:55 UTC, ridhomard commented on src/test/java/testCases/Validate_SelfExlcusion_Limits.java
> +				System.out.println("Positions in Self-exclusion more than 60, 60 is shown");
This seem doesn't executed ? need to check

2017-04-13 07:55 UTC, ridhomard commented on src/test/java/testCases/Validate_SelfExlcusion_Limits.java
> +			}
This seem doesn't executed ? need to check

2017-04-13 08:49 UTC, fanxuricky commented
Issues noted. I'm solving the issues.

2017-04-13 18:08 UTC, bijan2007 requested changes
Please resolve the conflicts

2017-04-21 02:49 UTC, bijan2007 commented on src/test/java/testCases/Validate_Limits.java
> +	// function to convert integer to string with comma
Create a CommonFunctions class under utility package and add this function

2017-04-21 02:59 UTC, bijan2007 requested changes
Can you please write all the validation logic in an Action and not inside the test cases ?

2017-04-21 03:03 UTC, fanxuricky commented
Noted, changes in process.

2017-04-24 03:25 UTC, bijan2007 approved these changes

2017-04-24 03:26 UTC, merged